name: generate animation

on:
  
  
  # allows to manually run the job at any time
  workflow_dispatch:
  

    
  

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 999

    
    steps:
      - name: Set snake color
        id: set_snake_color
        run: echo "::set-output name=color::$(shuf -n 1 -e 'purple' '#00e6de')"

      - name: Set snake speed
        id: set_snake_speed
        run: echo "::set-output name=speed::$(shuf -n 1 -e 'fast' 'slow' 'normal')"
        
      - name: Set dots color
        id: set_dots_color
        run: echo "::set-output name=dots_color::$(shuf -n 1 -e '#161b22,#631c03,#bd561c,#fa7a17,#fddf67' '#161b22,#0e4429,#006d32,#26a641,#39d353')"

      - name: Set snake size
        id: set_snake_size
        run: echo "::set-output name=size::$(shuf -n 1 -e '1' '2' '3' '4' '5' '6' '7')"
        
      - name: Set dots shape  
        id: set_dots_shape
        run: echo "::set-output name=shape::$(shuf -n 1 -e 'square' 'square-rounded' 'circle')"

      - name: Use outputs from previous steps
        run: |
          echo "SNAKE_COLOR is ${{ steps.set_snake_color.outputs.color }}"
          echo "SNAKE_SIZE is ${{ steps.set_snake_size.outputs.size }}"
          echo "SNAKE_SPEED is ${{ steps.set_snake_speed.outputs.speed }}"
          echo "DOT_COLOR is ${{ steps.set_dots_color.outputs.dots_color }}"
          echo "DOT_SHAPE is ${{ steps.set_dots_shape.outputs.shape }}"
     

        
      # generates a snake game from a github user (<github_user_name>) contributions graph, output a svg animation at <svg_out_path>
      - name: generate github-contribution-grid-snake.svg
        uses: Hollierose89/snk@main
        with:
          github_user_name: PaddyZz
          
          
          outputs: |
            dist/github-contribution-grid-snake-dark-snkSize5.svg?palette=github-dark&snake_size=5&color_dots=#161b22,#0e4429,#006d32,#26a641,#39d353&speed=fast&dot_shape=circle&color_snake=purple&hide_stack=true
            dist/github-contribution-grid-snake-dark-snkSize6.svg?palette=github-dark&snake_size=6&color_dots=#161b22,#0e4429,#006d32,#26a641,#39d353&speed=fast&dot_shape=circle&color_snake=purple&hide_stack=true
            
      # push the content of <build_dir> to a branch
      # the content will be available at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file> , or as github page
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
